/* Generated By:JavaCC: Do not edit this line. ModelGeneratorConstants.java */
package uti.parser;

public interface ModelGeneratorConstants {

  int EOF = 0;
  int BIG_COMMENT_BLA = 7;
  int SMALL_COMMENT_BLA = 8;
  int INTEGER_VALUE = 10;
  int FLOAT_VALUE = 11;
  int EXP = 12;
  int CHAR_VALUE = 13;
  int STRING_VALUE = 14;
  int PACKAGE_TOK = 15;
  int CLASS_TOK = 16;
  int INTERFACE_TOK = 17;
  int PUBLIC_TOK = 18;
  int PROTECTED_TOK = 19;
  int PRIVATE_TOK = 20;
  int FINAL_TOK = 21;
  int ABSTRACT_TOK = 22;
  int IMPLEMENTS_TOK = 23;
  int EXTENDS_TOK = 24;
  int THROWS_TOK = 25;
  int STATIC_TOK = 26;
  int IF_TOK = 27;
  int ELSE_TOK = 28;
  int DO_TOK = 29;
  int WHILE_TOK = 30;
  int FOR_TOK = 31;
  int IDENT = 32;
  int SYMIDENT = 33;
  int LKLAMMER = 34;
  int RKLAMMER = 35;
  int LGKLAMMER = 36;
  int RGKLAMMER = 37;
  int LEKLAMMER = 38;
  int REKLAMMER = 39;
  int SEMICOLON = 40;
  int COMMA = 41;
  int DOT = 42;

  int DEFAULT = 0;
  int BIG_COMMENT = 1;
  int SMALL_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<SMALL_COMMENT_BLA>",
    "<token of kind 9>",
    "<INTEGER_VALUE>",
    "<FLOAT_VALUE>",
    "<EXP>",
    "<CHAR_VALUE>",
    "<STRING_VALUE>",
    "\"package\"",
    "\"class\"",
    "\"interface\"",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"final\"",
    "\"abstract\"",
    "\"implements\"",
    "\"extends\"",
    "\"throws\"",
    "\"static\"",
    "\"if\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "\"for\"",
    "<IDENT>",
    "<SYMIDENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"]\"",
    "\"[\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\" = \"",
  };

}
