/* Generated By:JavaCC: Do not edit this line. ModelGeneratorConstants.java */
package uti.parser;

public interface ModelGeneratorConstants {

  int EOF = 0;
  int BIG_COMMENT_BLA = 7;
  int SMALL_COMMENT_BLA = 8;
  int INTEGER_VALUE = 10;
  int FLOAT_VALUE = 11;
  int EXP = 12;
  int CHAR_VALUE = 13;
  int STRING_VALUE = 14;
  int CODE_VALUE = 15;
  int PACKAGE_TOK = 16;
  int CLASS_TOK = 17;
  int INTERFACE_TOK = 18;
  int PUBLIC_TOK = 19;
  int PROTECTED_TOK = 20;
  int PRIVATE_TOK = 21;
  int FINAL_TOK = 22;
  int ABSTRACT_TOK = 23;
  int IMPLEMENTS_TOK = 24;
  int EXTENDS_TOK = 25;
  int THROWS_TOK = 26;
  int STATIC_TOK = 27;
  int IF_TOK = 28;
  int ELSE_TOK = 29;
  int DO_TOK = 30;
  int WHILE_TOK = 31;
  int FOR_TOK = 32;
  int INSTANCEOF_TOK = 33;
  int TRUE_TOK = 34;
  int FALSE_TOK = 35;
  int NULL_TOK = 36;
  int EXTERN_TOK = 37;
  int RETURN_TOK = 38;
  int BREAK_TOK = 39;
  int CONTINUE_TOK = 40;
  int NEW_TOK = 41;
  int IDENT = 42;
  int LKLAMMER = 43;
  int RKLAMMER = 44;
  int LGKLAMMER = 45;
  int RGKLAMMER = 46;
  int LEKLAMMER = 47;
  int REKLAMMER = 48;
  int SEMICOLON = 49;
  int COMMA = 50;
  int DOT = 51;

  int DEFAULT = 0;
  int BIG_COMMENT = 1;
  int SMALL_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<SMALL_COMMENT_BLA>",
    "<token of kind 9>",
    "<INTEGER_VALUE>",
    "<FLOAT_VALUE>",
    "<EXP>",
    "<CHAR_VALUE>",
    "<STRING_VALUE>",
    "<CODE_VALUE>",
    "\"package\"",
    "\"class\"",
    "\"interface\"",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"final\"",
    "\"abstract\"",
    "\"implements\"",
    "\"extends\"",
    "\"throws\"",
    "\"static\"",
    "\"if\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "\"for\"",
    "\"instanceof\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"externcode\"",
    "\"return\"",
    "\"break\"",
    "\"continue\"",
    "\"new\"",
    "<IDENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"]\"",
    "\"[\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"<<=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"?\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"++\"",
    "\"--\"",
  };

}
